/*
 * ============================================================
 * V5 - Align legacy payment/membership schema with JPA entities
 * ============================================================
 *
 * Legacy database:
 *   payments.id                 BIGINT identity
 *   memberships.payment_id      BIGINT
 *   payments.user_id            missing
 *
 * Current application:
 *   payments.id                 UUID
 *   memberships.payment_id      UUID
 *   payments.user_id            UUID -> users.id
 *
 * Existing payment relationships are preserved.
 */

/*
 * ------------------------------------------------------------
 * USER ROLE
 * ------------------------------------------------------------
 */

ALTER TABLE users
ADD COLUMN IF NOT EXISTS role VARCHAR(30)
NOT NULL DEFAULT 'ROLE_USER';


/*
 * ------------------------------------------------------------
 * PAYMENTS - TEMPORARY UUID ID
 * ------------------------------------------------------------
 */

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS id_uuid UUID;

/*
 * Generate deterministic UUIDs from the legacy payment IDs.
 *
 * No PostgreSQL UUID extension is required.
 */
UPDATE payments
SET id_uuid =
    (
        substr(md5('holy-matrimony-payment-' || id::text), 1, 8)
        || '-' ||
        substr(md5('holy-matrimony-payment-' || id::text), 9, 4)
        || '-' ||
        substr(md5('holy-matrimony-payment-' || id::text), 13, 4)
        || '-' ||
        substr(md5('holy-matrimony-payment-' || id::text), 17, 4)
        || '-' ||
        substr(md5('holy-matrimony-payment-' || id::text), 21, 12)
    )::uuid
WHERE id_uuid IS NULL;

ALTER TABLE payments
ALTER COLUMN id_uuid SET NOT NULL;


/*
 * ------------------------------------------------------------
 * PAYMENTS - USER RELATIONSHIP
 * ------------------------------------------------------------
 */

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS user_id UUID;

UPDATE payments p
SET user_id = u.id
FROM users u
WHERE p.user_id IS NULL
  AND lower(trim(p.email)) =
      lower(trim(u.email));

/*
 * Abort migration if any existing payment cannot be assigned
 * to an existing Holy Matrimony user.
 */
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM payments
        WHERE user_id IS NULL
    ) THEN
        RAISE EXCEPTION
            'Payment migration aborted: one or more payments could not be mapped to users';
    END IF;
END
$$;

ALTER TABLE payments
ALTER COLUMN user_id SET NOT NULL;


/*
 * ------------------------------------------------------------
 * ADD COLUMNS REQUIRED BY CURRENT PAYMENT ENTITY
 * ------------------------------------------------------------
 */

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS customer_name VARCHAR(255);

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS email VARCHAR(255);

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS phone VARCHAR(255);

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP;

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;


/*
 * Existing database already contains these values.
 * These UPDATE statements mainly make this migration safe
 * against older intermediate schemas.
 */

UPDATE payments
SET customer_name = COALESCE(
    NULLIF(trim(customer_name), ''),
    email,
    'Holy Matrimony Member'
)
WHERE customer_name IS NULL
   OR trim(customer_name) = '';

ALTER TABLE payments
ALTER COLUMN customer_name SET NOT NULL;

ALTER TABLE payments
ALTER COLUMN email SET NOT NULL;


/*
 * Current JPA Payment.amount is Integer.
 */
ALTER TABLE payments
ALTER COLUMN amount TYPE INTEGER
USING amount::INTEGER;


/*
 * Normalize signature type to match the entity.
 */
ALTER TABLE payments
ALTER COLUMN razorpay_signature TYPE VARCHAR(500)
USING razorpay_signature::VARCHAR(500);


/*
 * ------------------------------------------------------------
 * MEMBERSHIP - TEMPORARY UUID PAYMENT REFERENCE
 * ------------------------------------------------------------
 */

ALTER TABLE memberships
ADD COLUMN IF NOT EXISTS payment_id_uuid UUID;

UPDATE memberships m
SET payment_id_uuid = p.id_uuid
FROM payments p
WHERE m.payment_id IS NOT NULL
  AND m.payment_id = p.id;


/*
 * Verify every legacy membership payment reference was mapped.
 */
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM memberships
        WHERE payment_id IS NOT NULL
          AND payment_id_uuid IS NULL
    ) THEN
        RAISE EXCEPTION
            'Payment migration aborted: one or more membership payment references could not be migrated';
    END IF;
END
$$;


/*
 * ------------------------------------------------------------
 * DROP LEGACY PAYMENT CONSTRAINTS
 * ------------------------------------------------------------
 */

/*
 * Constraint name generated by the existing local database.
 */
ALTER TABLE memberships
DROP CONSTRAINT IF EXISTS fk5run8m20swc17petgw797jamq;

/*
 * Constraint name from the original V3 migration.
 */
ALTER TABLE memberships
DROP CONSTRAINT IF EXISTS fk_membership_payment;

/*
 * Existing Hibernate-generated one-to-one constraint.
 */
ALTER TABLE memberships
DROP CONSTRAINT IF EXISTS uk8o8hmv08uvha7q4wehw9fqwsm;

ALTER TABLE payments
DROP CONSTRAINT IF EXISTS payments_pkey;


/*
 * ------------------------------------------------------------
 * PRESERVE LEGACY IDS, PROMOTE UUID IDS
 * ------------------------------------------------------------
 */

/*
 * Keep the original numeric payment ID for audit/history.
 * It remains an identity-backed legacy reference.
 */
ALTER TABLE payments
RENAME COLUMN id TO legacy_id;

ALTER TABLE payments
RENAME COLUMN id_uuid TO id;


/*
 * Keep old membership numeric payment ID for audit/history.
 */
ALTER TABLE memberships
RENAME COLUMN payment_id TO legacy_payment_id;

ALTER TABLE memberships
RENAME COLUMN payment_id_uuid TO payment_id;


/*
 * ------------------------------------------------------------
 * NEW UUID CONSTRAINTS
 * ------------------------------------------------------------
 */

ALTER TABLE payments
ADD CONSTRAINT payments_pkey
PRIMARY KEY (id);

ALTER TABLE payments
ADD CONSTRAINT fk_payment_user
FOREIGN KEY (user_id)
REFERENCES users(id);


/*
 * One membership can refer to one payment.
 */
CREATE UNIQUE INDEX IF NOT EXISTS
uk_memberships_payment_id
ON memberships(payment_id)
WHERE payment_id IS NOT NULL;

ALTER TABLE memberships
ADD CONSTRAINT fk_membership_payment
FOREIGN KEY (payment_id)
REFERENCES payments(id);


/*
 * ------------------------------------------------------------
 * CURRENT MEMBERSHIP ENTITY COLUMNS
 * ------------------------------------------------------------
 */

ALTER TABLE memberships
ADD COLUMN IF NOT EXISTS auto_renew BOOLEAN
NOT NULL DEFAULT FALSE;

ALTER TABLE memberships
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;


/*
 * ------------------------------------------------------------
 * PAYMENT LOOKUP INDEXES
 * ------------------------------------------------------------
 */

CREATE INDEX IF NOT EXISTS idx_payment_user
ON payments(user_id);

CREATE INDEX IF NOT EXISTS idx_payment_order
ON payments(razorpay_order_id);

CREATE INDEX IF NOT EXISTS idx_membership_user
ON memberships(user_id);

CREATE INDEX IF NOT EXISTS idx_membership_payment
ON memberships(payment_id);


/*
 * Razorpay IDs should be unique whenever populated.
 */
CREATE UNIQUE INDEX IF NOT EXISTS
uk_payments_razorpay_order_id
ON payments(razorpay_order_id)
WHERE razorpay_order_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS
uk_payments_razorpay_payment_id
ON payments(razorpay_payment_id)
WHERE razorpay_payment_id IS NOT NULL;


