ALTER TABLE users
ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE users
ADD COLUMN IF NOT EXISTS status_reason VARCHAR(500);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS status_changed_at TIMESTAMP;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS status_changed_by UUID;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS profile_completion INTEGER NOT NULL DEFAULT 0;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS membership_type VARCHAR(30) NOT NULL DEFAULT 'FREE';

ALTER TABLE users
ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP;