spring.application.name=holy-matrimony-backend

server.port=8080

# PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/holymatrimony
spring.datasource.username=hm_user
spring.datasource.password=Hm@2026Secure
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Flyway

spring.flyway.enabled=false

# JWT

jwt.secret=HolyMatrimonySecureSecretKey2026HolyMatrimonySecureSecretKey
jwt.expiration=86400000